"""
Loss functions for SMMILe training.

Paper: Gao et al. (2025) "SMMILe enables accurate spatial quantification in
digital pathology using multiple-instance learning", Nature Cancer.
DOI: 10.1038/s43018-025-01060-8

Equations referenced:
  Eq. (10) — L_cons : consistency loss for negative bags
  Eq. (14) — L_cls  : bag classification loss (four bag-prediction variants)
  Eq. (15) — L_ref  : instance refinement loss (progressive pseudo-labels)
  Eq. (16) — L_mrf  : superpatch-based MRF smoothness loss

Stage composition:
  Stage 1 : L_cls  [+ L_cons if dataset has a normal class]
  Stage 2 : L_cls + L_ref + L_mrf  [+ L_cons if applicable]

Note: UBC-OCEAN has no explicit normal class — L_cons is always zero there.
"""

from __future__ import annotations

from typing import Sequence

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _to_onehot(label: int | torch.Tensor, n_classes: int, device: torch.device) -> torch.Tensor:
    """Convert int label or (n_classes,) tensor to float one-hot (n_classes,)."""
    if isinstance(label, int):
        t = torch.zeros(n_classes, device=device)
        t[label] = 1.0
        return t
    return label.float().to(device)


def _pos_class(label: int | torch.Tensor) -> int:
    """Return the positive class index for a single-label bag."""
    if isinstance(label, int):
        return label
    return int(label.argmax().item())


# ---------------------------------------------------------------------------
# L_cls — Classification loss (Eq. 14)
# ---------------------------------------------------------------------------

class ClassificationLoss(nn.Module):
    """Bag-level BCE classification loss computed over up to four bag-prediction
    variants (raw, drop, sampled, drop+sampled) and independently per category.

    SMMILe Eq. (14):

        L_cls = (1/|V|) ∑_{v ∈ V} BCE(bag_logits_v, y_one_hot)

    where V = {raw, drop, sampled, drop+sampled} are the four variants
    generated by the combinations of InD and InS.  Averaging over all
    variants encourages the model to produce consistent predictions under
    different regularisation regimes.

    ``forward`` is deliberately flexible:
      - Single (C,) tensor  → treated as a single variant (backward compat)
      - List of (C,) tensors → BCE averaged over all variants
      - Model output dict   → all ``bag_logits*`` keys are collected

    Parameters
    ----------
    n_classes : int
        Number of cancer subtypes C (5 for UBC-OCEAN).
    """

    # Keys in the model output dict that constitute the four variants.
    _VARIANT_KEYS = (
        "bag_logits_raw",
        "bag_logits_drop",
        "bag_logits_sampled",
        "bag_logits",
    )

    def __init__(self, n_classes: int = 5) -> None:
        super().__init__()
        self.n_classes = n_classes
        self.bce = nn.BCEWithLogitsLoss()

    # ------------------------------------------------------------------

    def forward(
        self,
        bag_logits: torch.Tensor | list[torch.Tensor] | dict,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        """Compute L_cls.

        Parameters
        ----------
        bag_logits : (C,) tensor  |  list of (C,) tensors  |  model-output dict
        label      : int (class index) or (C,) one-hot tensor.

        Returns
        -------
        Scalar tensor — mean BCE over all provided variants.
        """
        if isinstance(bag_logits, dict):
            variants = [
                bag_logits[k]
                for k in self._VARIANT_KEYS
                if k in bag_logits
            ]
            if not variants:
                raise KeyError(
                    "ClassificationLoss received a dict but found none of "
                    f"{self._VARIANT_KEYS}"
                )
        elif isinstance(bag_logits, (list, tuple)):
            variants = list(bag_logits)
        else:
            variants = [bag_logits]

        device = variants[0].device
        target = _to_onehot(label, self.n_classes, device)  # (C,)

        total = sum(self.bce(v, target) for v in variants)
        return total / len(variants)


# ---------------------------------------------------------------------------
# L_cons — Consistency loss for negative bags (Eq. 10)
# ---------------------------------------------------------------------------

class ConsistencyLoss(nn.Module):
    """Uniform-attention consistency loss for negative (normal) bags.

    SMMILe Eq. (10):

        L_cons = (1/C) ∑_c MSE(a_c, 1/K · **1**)

    For a negative bag (slide with no cancer), no spatial region should be
    discriminative, so the per-category attention weights should be uniform
    over all K instances.  For positive (cancer) bags the loss is zero.

    Note: Not used for UBC-OCEAN (all slides are cancerous).  Implementation
    is provided for completeness and compatibility with datasets that include
    a normal class (e.g. Camelyon16).

    Parameters
    ----------
    n_classes        : int  Number of categories.
    normal_class_idx : int  Index of the normal/negative class in the label.
                            Use -1 to indicate the LAST class.
    """

    def __init__(self, n_classes: int = 5, normal_class_idx: int = -1) -> None:
        super().__init__()
        self.n_classes = n_classes
        self.normal_class_idx = normal_class_idx

    # ------------------------------------------------------------------

    def forward(
        self,
        attn: torch.Tensor,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        """Compute L_cons.

        Parameters
        ----------
        attn  : (n_classes, K) full-bag softmax attention weights.
                Must be the *full-bag* attention (not pseudo-bag), so that
                K matches the number of instances.
        label : int or (n_classes,) one-hot ground-truth label.

        Returns
        -------
        Scalar tensor — MSE against uniform attention, or 0 for positive bags.
        """
        # Determine whether this bag is normal/negative.
        norm_idx = self.normal_class_idx % self.n_classes   # handle -1
        if isinstance(label, int):
            is_normal = (label == norm_idx)
        else:
            is_normal = bool(label[norm_idx].item() > 0.5)

        if not is_normal:
            return torch.zeros(1, device=attn.device).squeeze()

        # Eq. (10): enforce uniform attention per category.
        K = attn.shape[1]
        uniform = torch.full_like(attn, 1.0 / K)  # (C, K)
        return F.mse_loss(attn, uniform)


# ---------------------------------------------------------------------------
# L_ref — Instance refinement loss (Eq. 15)
# ---------------------------------------------------------------------------

class RefinementLoss(nn.Module):
    """Progressive pseudo-label cross-entropy loss for all N refinement layers.

    SMMILe Eq. (15):

        L_ref = (1/N) ∑_{n=1}^{N}  CE( v_n(h_{sel}),  ŷ_{sel,n} )

    where for layer n:
      • Layer 1: pseudo-labels ŷ_{sel,1} come from the Stage 1 attention
        weights (top-θ% → positive class; bottom-θ% → background C).
      • Layer n>1: pseudo-labels ŷ_{sel,n} come from softmax(v_{n-1}(h))
        **detached** (no gradient back through pseudo-label generation).

    The top-θ% instances with the highest score for the positive class are
    assigned pseudo-label = pos_class.  The bottom-θ% are assigned label C
    (background / "not this class").  The remaining (1-2θ) fraction are
    ignored (masked out of the CE).

    Parameters
    ----------
    theta     : float  Top/bottom fraction to pseudo-label (default 0.10).
    n_classes : int    Number of cancer subtypes C.  Refinement layers output
                       (C+1)-dim logits (C classes + 1 background).
    """

    def __init__(self, theta: float = 0.10, n_classes: int = 5) -> None:
        super().__init__()
        self.theta = theta
        self.n_classes = n_classes

    # ------------------------------------------------------------------

    def _pseudo_labels_from_scores(
        self,
        scores: torch.Tensor,   # (K,) or (K, C+1) — score for pos class
        K: int,
        pos_class: int,
        device: torch.device,
        source: str = "attn",   # "attn" | "softmax"
    ) -> torch.Tensor:
        """Build a (K,) pseudo-label tensor with -1 for unlabelled instances.

        Parameters
        ----------
        scores : (K,) attention weights for pos_class (source='attn')
                 (K, C+1) softmax probabilities   (source='softmax')
        """
        if source == "softmax":
            scores = scores[:, pos_class]   # (K,)

        n_sel = max(1, int(K * self.theta))
        top_idx = scores.topk(n_sel).indices                     # top-θ%
        bot_idx = scores.topk(n_sel, largest=False).indices      # bottom-θ%

        pseudo = torch.full((K,), -1, dtype=torch.long, device=device)
        pseudo[top_idx] = pos_class
        pseudo[bot_idx] = self.n_classes   # background label = C
        return pseudo

    # ------------------------------------------------------------------

    def forward(
        self,
        ref_all_logits: Sequence[torch.Tensor],
        attn: torch.Tensor,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        """Compute L_ref.

        Parameters
        ----------
        ref_all_logits : list of N tensors, each (K, n_classes + 1)
            Raw logits from all N refinement layers (v_1 … v_N).
        attn : (n_classes, K)
            Full-bag softmax attention from Stage 1 detector.
            Used to generate pseudo-labels for layer 1.
        label : int or (n_classes,) one-hot.

        Returns
        -------
        Scalar — mean CE loss across N refinement layers.
        """
        pos_class = _pos_class(label)
        device    = ref_all_logits[0].device
        K         = ref_all_logits[0].shape[0]

        total = torch.zeros(1, device=device).squeeze()

        for n, logits_n in enumerate(ref_all_logits):
            # --- Generate pseudo-labels for this layer -----------------
            if n == 0:
                # Layer 1: use Stage 1 attention weights over K instances.
                # attn is (C, K), guaranteed by smmile.py fix.
                pseudo = self._pseudo_labels_from_scores(
                    attn[pos_class],   # (K,)
                    K, pos_class, device, source="attn",
                )
            else:
                # Layer n>1: use softmax of previous layer (detached).
                prev_probs = F.softmax(ref_all_logits[n - 1].detach(), dim=-1)  # (K, C+1)
                pseudo = self._pseudo_labels_from_scores(
                    prev_probs, K, pos_class, device, source="softmax",
                )

            # --- Cross-entropy on labelled instances only ---------------
            valid = pseudo != -1
            if valid.any():
                total = total + F.cross_entropy(logits_n[valid], pseudo[valid])

        return total / max(1, len(ref_all_logits))


# ---------------------------------------------------------------------------
# L_mrf — Superpatch MRF smoothness loss (Eq. 16)
# ---------------------------------------------------------------------------

class MRFLoss(nn.Module):
    """Superpatch-based Markov Random Field smoothness loss.

    SMMILe Eq. (16):

        L_mrf = λ1 · E_1  +  λ2 · E_2

    First-order energy E_1 — intra-superpatch consistency:
        For each superpatch s, penalise the variance of predicted class
        probabilities among patches belonging to that superpatch.

            E_1 = (1/|S|) ∑_{s ∈ S}  mean_c Var_{k ∈ s}( p_n(k)_c )

        where p_n(k) = softmax(v_N(h_k))[:C] is the C-dim class probability
        for instance k from the last refinement layer.

    Second-order energy E_2 — inter-superpatch smoothness:
        Neighbouring superpatches should have similar mean predicted
        distributions.

        When ``coords`` (K, 2) are provided:
            • Compute each superpatch's centre = mean of its patch coords.
            • Two superpatches are adjacent if their centre distance ≤
              ``adj_radius`` (default: 1.5 × median nearest-neighbour distance
              among superpatch centres, auto-computed if not set).
            • E_2 = (1/|N|) ∑_{(s,t) ∈ N}  KL( p̄_s || p̄_t )
              where p̄_s = mean prediction over patches in superpatch s.

        When ``coords`` is None (fall-back):
            • E_2 = Var( p̄_s )  — variance of superpatch mean predictions
              across all superpatches S (global smoothness regulariser).

    Parameters
    ----------
    lambda1    : float  Weight for E_1 (intra-SP consistency).
    lambda2    : float  Weight for E_2 (inter-SP smoothness).
    n_classes  : int    Number of cancer subtypes C.
    adj_radius : float | None
        Maximum centre-to-centre distance (in coord units) for two
        superpatches to be considered adjacent.  Auto-inferred from coords
        if None (recommended).
    """

    def __init__(
        self,
        lambda1: float = 0.8,
        lambda2: float = 0.2,
        n_classes: int = 5,
        adj_radius: float | None = None,
    ) -> None:
        super().__init__()
        self.lambda1    = lambda1
        self.lambda2    = lambda2
        self.n_classes  = n_classes
        self.adj_radius = adj_radius

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _sp_means(
        probs: torch.Tensor,      # (K, C)
        superpixels: torch.Tensor,  # (K,)
        sp_ids: torch.Tensor,       # (N_sp,)
    ) -> torch.Tensor:
        """Return (N_sp, C) tensor of per-superpatch mean probabilities."""
        means = torch.stack(
            [probs[superpixels == sid].mean(dim=0) for sid in sp_ids],
            dim=0,
        )
        return means   # (N_sp, C)

    @staticmethod
    def _infer_adj_radius(centers: torch.Tensor) -> float:
        """Estimate adjacency radius as 1.5× median nearest-neighbour distance."""
        N = centers.shape[0]
        if N <= 1:
            return float("inf")
        # Pairwise L2 distances: (N, N)
        diff = centers.unsqueeze(0) - centers.unsqueeze(1)   # (N, N, 2)
        dists = diff.norm(dim=-1)                             # (N, N)
        # Exclude self-distance by setting diagonal to +inf
        dists.fill_diagonal_(float("inf"))
        nn_dists = dists.min(dim=1).values                   # (N,)
        return float(nn_dists.median().item() * 1.5)

    # ------------------------------------------------------------------

    def forward(
        self,
        ref_logits: torch.Tensor,
        superpixels: torch.Tensor,
        coords: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Compute L_mrf.

        Parameters
        ----------
        ref_logits  : (K, n_classes + 1)
            Logits from the last refinement layer v_N.
        superpixels : (K,)
            SLIC superpatch label per instance (integer IDs).
        coords      : (K, 2) optional
            Spatial coordinates (x, y in pixels) of each patch centre.
            Used to determine superpatch adjacency for E_2.
            If None, a global variance term is used for E_2 instead.

        Returns
        -------
        Scalar MRF loss.
        """
        probs  = F.softmax(ref_logits[:, : self.n_classes], dim=-1)  # (K, C)
        sp_ids = superpixels.unique()                                  # (N_sp,)
        N_sp   = len(sp_ids)

        # ----------------------------------------------------------------
        # First-order energy E_1: intra-superpatch prediction variance
        # ----------------------------------------------------------------
        e1 = torch.zeros(1, device=ref_logits.device).squeeze()
        for sid in sp_ids:
            mask = superpixels == sid
            if mask.sum() < 2:
                continue
            sp_var = probs[mask].var(dim=0).mean()   # scalar
            e1 = e1 + sp_var
        e1 = e1 / max(1, N_sp)

        # ----------------------------------------------------------------
        # Second-order energy E_2: inter-superpatch smoothness
        # ----------------------------------------------------------------
        sp_mean_probs = self._sp_means(probs, superpixels, sp_ids)  # (N_sp, C)
        # Clamp for numerical stability in KL divergence
        sp_mean_probs = sp_mean_probs.clamp(min=1e-8)
        sp_mean_probs = sp_mean_probs / sp_mean_probs.sum(dim=-1, keepdim=True)

        if coords is not None and N_sp >= 2:
            # Compute superpatch centres from patch coordinates
            centers = torch.stack(
                [coords[superpixels == sid].float().mean(dim=0) for sid in sp_ids],
                dim=0,
            )  # (N_sp, 2)

            radius = (
                self.adj_radius
                if self.adj_radius is not None
                else self._infer_adj_radius(centers)
            )

            # Pairwise distances between superpatch centres
            diff  = centers.unsqueeze(0) - centers.unsqueeze(1)  # (N_sp, N_sp, 2)
            dists = diff.norm(dim=-1)                             # (N_sp, N_sp)

            # Build adjacency mask (upper triangle only to avoid double-counting)
            adj   = (dists <= radius) & (dists > 0)              # (N_sp, N_sp)
            idx_s, idx_t = adj.triu().nonzero(as_tuple=True)

            if len(idx_s) > 0:
                p = sp_mean_probs[idx_s]   # (|N|, C) — query distributions
                q = sp_mean_probs[idx_t]   # (|N|, C) — reference distributions
                # Symmetric KL: KL(p||q) + KL(q||p)
                kl_pq = (p * (p / q).log()).sum(dim=-1)
                kl_qp = (q * (q / p).log()).sum(dim=-1)
                e2    = ((kl_pq + kl_qp) / 2.0).mean()
            else:
                e2 = torch.zeros(1, device=ref_logits.device).squeeze()
        else:
            # Fall-back: variance of superpatch mean predictions (global smoothness)
            if N_sp >= 2:
                global_mean = sp_mean_probs.mean(dim=0, keepdim=True)   # (1, C)
                e2 = ((sp_mean_probs - global_mean) ** 2).mean()
            else:
                e2 = torch.zeros(1, device=ref_logits.device).squeeze()

        return self.lambda1 * e1 + self.lambda2 * e2


# ---------------------------------------------------------------------------
# SMMILeTotalLoss — Integrates all components
# ---------------------------------------------------------------------------

class SMMILeTotalLoss(nn.Module):
    """Complete SMMILe training objective.

    Stage 1 : L_total = w_cls · L_cls  [+ w_cons · L_cons]
    Stage 2 : L_total = w_cls · L_cls  +  w_ref · L_ref  +  w_mrf · L_mrf
                        [+ w_cons · L_cons]

    Parameters
    ----------
    n_classes        : Number of cancer subtypes C.
    theta            : Pseudo-label fraction for L_ref (default 0.10).
    lambda1          : MRF intra-SP weight (default 0.8).
    lambda2          : MRF inter-SP weight (default 0.2).
    adj_radius       : Adjacency radius for MRF E_2 (auto if None).
    cls_weight       : Weight w_cls for L_cls.
    ref_weight       : Weight w_ref for L_ref.
    mrf_weight       : Weight w_mrf for L_mrf.
    cons_weight      : Weight w_cons for L_cons (0 = disabled).
    normal_class_idx : Index of the normal class for L_cons.
    stage            : Training stage (1 or 2); controls which losses are active.
    """

    def __init__(
        self,
        n_classes: int = 5,
        theta: float = 0.10,
        lambda1: float = 0.8,
        lambda2: float = 0.2,
        adj_radius: float | None = None,
        cls_weight: float = 1.0,
        ref_weight: float = 1.0,
        mrf_weight: float = 1.0,
        cons_weight: float = 0.0,
        normal_class_idx: int = -1,
        stage: int = 1,
    ) -> None:
        super().__init__()
        self.stage       = stage
        self.cls_weight  = cls_weight
        self.ref_weight  = ref_weight
        self.mrf_weight  = mrf_weight
        self.cons_weight = cons_weight

        self.cls_loss  = ClassificationLoss(n_classes=n_classes)
        self.cons_loss = ConsistencyLoss(n_classes=n_classes, normal_class_idx=normal_class_idx)
        self.ref_loss  = RefinementLoss(theta=theta, n_classes=n_classes)
        self.mrf_loss  = MRFLoss(
            lambda1=lambda1,
            lambda2=lambda2,
            n_classes=n_classes,
            adj_radius=adj_radius,
        )

    # ------------------------------------------------------------------

    def forward(
        self,
        model_out: dict,
        label: int | torch.Tensor,
        superpixels: torch.Tensor,
        coords: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        """Compute the total training loss for one WSI.

        Parameters
        ----------
        model_out   : dict returned by SMMILe.forward().
        label       : Ground-truth bag label (int or (C,) one-hot).
        superpixels : (K,) SLIC superpatch IDs per instance.
        coords      : (K, 2) patch spatial coordinates (optional, for MRF E_2).

        Returns
        -------
        (total_loss, loss_dict)
            total_loss : scalar tensor — the full weighted sum.
            loss_dict  : dict with per-component scalar values for logging.
        """
        loss_dict: dict[str, torch.Tensor] = {}

        # ---- L_cls (always active) ----
        l_cls = self.cls_loss(model_out, label)
        loss_dict["l_cls"] = l_cls
        total = self.cls_weight * l_cls

        # ---- L_cons (optional — off for UBC-OCEAN) ----
        if self.cons_weight > 0.0 and "attn" in model_out:
            l_cons = self.cons_loss(model_out["attn"], label)
            loss_dict["l_cons"] = l_cons
            total = total + self.cons_weight * l_cons

        # ---- Stage 2 losses ----
        if self.stage >= 2:
            # L_ref — requires all refinement layer outputs and full-bag attn
            if "ref_all_logits" in model_out:
                l_ref = self.ref_loss(
                    model_out["ref_all_logits"],
                    model_out["attn"],      # (C, K) full-bag attention
                    label,
                )
            elif "ref_logits" in model_out:
                # Fall-back: treat single layer as a one-element list
                l_ref = self.ref_loss(
                    [model_out["ref_logits"]],
                    model_out["attn"],
                    label,
                )
            else:
                l_ref = torch.zeros(1, device=superpixels.device).squeeze()

            loss_dict["l_ref"] = l_ref
            total = total + self.ref_weight * l_ref

            # L_mrf — requires last refinement layer logits
            ref_logits = model_out.get("ref_logits")
            if ref_logits is not None:
                l_mrf = self.mrf_loss(ref_logits, superpixels, coords)
                loss_dict["l_mrf"] = l_mrf
                total = total + self.mrf_weight * l_mrf

        loss_dict["total"] = total
        return total, loss_dict


# ---------------------------------------------------------------------------
# Backward-compatible aliases for the existing Trainer
# ---------------------------------------------------------------------------
# The Trainer in trainer.py imports ClsLoss, ConsLoss, MRFLoss, RefLoss with
# the original (pre-refactor) call signatures.  These thin wrappers preserve
# that API without changing the Trainer.

class ClsLoss(nn.Module):
    """Backward-compat wrapper — single (C,) bag_logits, one label."""

    def __init__(self, n_classes: int = 5) -> None:
        super().__init__()
        self._inner = ClassificationLoss(n_classes=n_classes)

    def forward(
        self,
        bag_logits: torch.Tensor,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        return self._inner(bag_logits, label)


class RefLoss(nn.Module):
    """Backward-compat wrapper — single ref_logits layer (not a list)."""

    def __init__(self, theta: float = 0.10, n_classes: int = 5) -> None:
        super().__init__()
        self._inner = RefinementLoss(theta=theta, n_classes=n_classes)

    def forward(
        self,
        ref_logits: torch.Tensor,
        attn: torch.Tensor,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        return self._inner([ref_logits], attn, label)


class ConsLoss(nn.Module):
    """Backward-compat wrapper — accepts ref_logits (Stage 2) instead of attn.

    The original ConsLoss penalised background-prediction confidence on
    ref_logits for normal bags.  The new ConsistencyLoss operates on
    attention weights instead (more faithful to Eq. 10).  This wrapper
    keeps the old interface by computing entropy of the background column.
    """

    def __init__(self, normal_class_idx: int = -1) -> None:
        super().__init__()
        self.normal_class_idx = normal_class_idx

    def forward(
        self,
        ref_logits: torch.Tensor,
        label: int | torch.Tensor,
    ) -> torch.Tensor:
        n_classes = ref_logits.shape[1] - 1   # C+1 dim, background is last
        norm_idx  = self.normal_class_idx % (n_classes + 1)

        if isinstance(label, int):
            is_normal = (label == norm_idx)
        else:
            is_normal = bool(label[norm_idx].item() > 0.5)

        if not is_normal:
            return torch.zeros(1, device=ref_logits.device).squeeze()

        # Encourage all instances to predict background (last column)
        probs  = F.softmax(ref_logits, dim=-1)
        bg_prob = probs[:, -1].clamp(min=1e-8)
        return -bg_prob.log().mean()
